server:
  port: 80

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.133:23451/appstore?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: postgres
    password: postgres
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

